Jason/renderer -> Code Review
Wagk/shiny pull request #2
Opened 2018-02-07 06:06 UTC by crasong

Hello. Not sure what else to write here.

2018-02-07 07:13 UTC, julwrites requested changes
There's plenty to change, some just code conventions to pick up and some good practices.

2018-02-07 07:13 UTC, julwrites commented on shiny/main.cpp
> +#include "renderer.h"
Would be good if these were path includes (e.g. #include <window.h>) to eliminate some pain if folder structures change.

2018-02-07 07:13 UTC, julwrites commented on shiny/main.cpp
> +//class HelloTriangleApplication {
Remove dead code as much as possible. It's versioned, it can be restored if necessary.

2018-02-07 07:13 UTC, julwrites commented on shiny/main.cpp
> +    shiny::renderer renderer; renderer.init();
One statement on each line please. It will help to provide a logical separation between constructor failure and init failure as well.

2018-02-07 07:13 UTC, julwrites commented on shiny/renderer.cpp
> +          : m_bad_init(false)
Why have m_bad_init? Just throw if it fails to construct, would be more explicit.

2018-02-07 07:13 UTC, julwrites commented on shiny/renderer.cpp
> +     renderer::find_queue_families(VkPhysicalDevice device) const
It is good habit to pass all parameters as const reference or r-value references (which would deteriorate into const references if able). That way you save on a lot of copying during passing in case the objects being passed are not built in types. That being said, VkPhysicalDevice might be an int, so maybe not necessary in this case.

2018-02-07 07:13 UTC, julwrites commented on shiny/renderer.h
> +#include "vk/logical_device.h"
Similarly would be nice to have this as path includes.

2018-02-07 07:13 UTC, julwrites commented on shiny/renderer.h
> +          vk::instance m_instance;
This looks a bit like a singleton structure. Is it? If so, there should be no exposed constructor.

2018-02-07 07:13 UTC, julwrites commented on shiny/shiny.vcxproj
> +    <ClCompile Include="vk\instance.cpp" />
I believe you can set an include/source directory, rather than include each file individually. Do check.

2018-02-07 07:13 UTC, julwrites commented on shiny/vk/instance.cpp
> +          else {
Actually, don't need the else block. Would be a little neater too, since you then have a default return case.

2018-02-07 07:13 UTC, julwrites commented on shiny/vk/instance.cpp
> +                    if (elem.layerName == layer_name) { available = true; }
Split up the code. An extra 2 lines is fine, we don't need to squeeze everything into one line. If you feel the need to squeeze code like that, something is wrong with the code and it should be split up.

2018-02-07 07:13 UTC, julwrites commented on shiny/vk/instance.cpp
> +                    if (elem == glfwExtensions[i]) { exists = true; }
Can break after finding.

2018-02-07 07:13 UTC, julwrites commented on shiny/vk/instance.cpp
> +          , m_has_init(false)
@Wagk remind me again, why do a m_has_init flag?

2018-02-07 07:13 UTC, julwrites commented on shiny/vk/instance.cpp
> +          vkEnumerateInstanceExtensionProperties(nullptr, &ext_count, nullptr);
Is there no better way to do this? Seems a little silly to call the same function twice.

2018-02-07 07:13 UTC, julwrites commented on shiny/vk/logical_device.cpp
> +    void vk::logical_device::create_logical_device(renderer* iRenderer, bool enableValidationLayers, std::vector<const char*> validation_layers){
Please pass renderer either as a reference, or encapsulate it in a smart pointer (assuming that is the convention to follow). Also, pass any non built-in type as a r-value reference or const reference.

2018-02-07 07:13 UTC, julwrites commented on shiny/vk/logical_device.h
> +        logical_device();
If we are not going to implement anything in these, don't need to declare them. Compiler will generate default declarations and definitions for constructor and destructor.

2018-02-07 07:13 UTC, julwrites commented on shiny/vk/physical_device.cpp
> +     physical_device::physical_device()
Empty functions are as good as dead code.

2018-02-07 07:13 UTC, julwrites commented on shiny/window.cpp
> +  window::window(int width, int height)
Why is indentation different here than in the other files...?

2018-02-07 07:28 UTC, Wagk commented on shiny/renderer.cpp
> +     renderer::find_queue_families(VkPhysicalDevice device) const
afaik `VkPhysicalDevice` is implemented as an opaque pointer, so...

2018-02-07 07:29 UTC, Wagk commented on shiny/vk/instance.cpp
> +          vkEnumerateInstanceExtensionProperties(nullptr, &ext_count, nullptr);
no better way afaik, these are vulkan interfaces

2018-02-07 14:26 UTC, Wagk commented on shiny/shiny.vcxproj
> +    <ClCompile Include="vk\instance.cpp" />
This should have been fixed by the latest pull request

2018-02-07 16:48 UTC, wagk requested changes

2018-02-07 16:48 UTC, Wagk commented on changelog.txt
> +// instead of "mPhysicalDevice->find_queue_families(mPhysicalDevice);"
`mPhysicalDevice` is a member field though, so there's no need to pass it in as a argument, it is always available for use

2018-02-07 16:48 UTC, Wagk commented on changelog.txt
> +// Let me know if this is the right call or not.
I would dislike exposing vulkan primitives directly through a renderer, to a user who rightfully should not care. We should try to keep everything as internal as possible

2018-02-08 02:05 UTC, julwrites commented on changelog.txt
> +// instead of "mPhysicalDevice->find_queue_families(mPhysicalDevice);"
Unless you want to treat renderer as a singleton object that could manage any physical device it is given?

2018-02-08 16:15 UTC, Wagk commented
Going to close this until there's more code and people can work without stepping on each other's toes

2018-02-08 16:15 UTC, closed without merging

2018-02-08 16:15 UTC, Wagk commented on changelog.txt
> +// instead of "mPhysicalDevice->find_queue_families(mPhysicalDevice);"
I would ideally want a queuemanager for that. There needs to be some intermediate managment levels